### PR TITLE
fix: preserve source pin identity in KiCad pad numbers (#212)

### LINKED ISSUE #212: KiCad export renumbers custom footprint pads by array order instead of preserving source pin identity
# KiCad export renumbers custom footprint pads by array order instead of preserving source pin identity

## Summary

`tsci export -f kicad_pcb` appears to assign KiCad pad numbers from the order of `pcb_smtpad` /
`pcb_plated_hole` elements rather than from the pad’s source pin identity.

This breaks custom footprints where pads are listed in physical layout order instead of numeric pin order,
which is common for SOIC/SSOP/QFN-style parts and connectors with gapped/non-1-indexed pin numbers.

The intermediate `circuit-json` is correct: `pcb_smtpad.port_hints`, `pcb_smtpad.pcb_port_id`,
`pcb_port.source_port_id`, and `source_port.pin_number` preserve the intended pin identity. The KiCad export
loses that identity and emits sequential pad labels.

## Tested Versions

Still reproduces on latest published packages as of 2026-04-19:

```
tscircuit:              0.0.1646
circuit-json-to-kicad:  0.0.105
circuit-json:           0.0.416
```

## Minimal Reproduction

repro.tsx:
```
export default () => (
  <board width="20mm" height="10mm" routingDisabled>
    <chip
      name="U1"
      pcbX={0}
      pcbY={0}
      pinLabels={{
        pin1: "P1",
        pin2: "P2",
        pin3: "P3",
        pin4: "P4",
      }}
      footprint={
        <footprint>
          <smtpad portHints={["pin4"]} pcbX="-3mm" pcbY="0mm" width="0.8mm" height="1.5mm" shape="rect" />
          <smtpad portHints={["pin3"]} pcbX="-1mm" pcbY="0mm" width="0.8mm" height="1.5mm" shape="rect" />
          <smtpad portHints={["pin2"]} pcbX="1mm" pcbY="0mm" width="0.8mm" height="1.5mm" shape="rect" />
          <smtpad portHints={["pin1"]} pcbX="3mm" pcbY="0mm" width="0.8mm" height="1.5mm" shape="rect" />
        </footprint>
      }
    />
  </board>
)
```
Commands:
```
npm install tscircuit@latest circuit-json-to-kicad@latest circuit-json@latest

./node_modules/.bin/tsci export repro.tsx -f circuit-json -o repro.circuit.json
./node_modules/.bin/tsci export repro.tsx -f kicad_pcb -o repro.kicad_pcb
```

## Expected Behavior

KiCad pad numbers should preserve the source pin identity:
```
(pad "4" ... (at -3 0 0))
(pad "3" ... (at -1 0 0))
(pad "2" ... (at  1 0 0))
(pad "1" ... (at  3 0 0))
```
## Actual Behavior

KiCad pad numbers are sequential by pad array order:
```
(pad "1" ... (at -3 0 0))
(pad "2" ... (at -1 0 0))
(pad "3" ... (at  1 0 0))
(pad "4" ... (at  3 0 0))
```
## Circuit JSON Shows Correct Pin Identity

The intermediate circuit-json preserves the intended pin identity:
```
pcb_smtpad_0  port_hints=["pin4"]  x=-3  y=0
pcb_smtpad_1  port_hints=["pin3"]  x=-1  y=0
pcb_smtpad_2  port_hints=["pin2"]  x=1   y=0
pcb_smtpad_3  port_hints=["pin1"]  x=3   y=0
```
It also has enough structured information to avoid guessing from port_hints:
```
{
  "type": "pcb_smtpad",
  "pcb_smtpad_id": "pcb_smtpad_0",
  "pcb_component_id": "pcb_component_0",
  "pcb_port_id": "pcb_port_3",
  "port_hints": ["pin4"],
  "x": -3,
  "y": 0
}

{
  "type": "pcb_port",
  "pcb_port_id": "pcb_port_3",
  "pcb_component_id": "pcb_component_0",
  "source_port_id": "source_port_3",
  "x": -3,
  "y": 0
}

{
  "type": "source_port",
  "source_port_id": "source_port_3",
  "name": "P4",
  "pin_number": 4,
  "port_hints": ["P4", "pin4", "4"]
}
```
So the KiCad pad number should be derived from source_port.pin_number, or from a stable pin-like port_hints
fallback when no source port exists.

## Why This Matters

KiCad pad numbers are not decorative. They are the physical package pin identity used by:

- KiCad inspection and DRC workflows
- downstream fabrication/assembly checks
- comparison against LCSC/EasyEDA footprints
- generated BOM/CPL/package validation workflows
- human review of exported footprints

If portHints={["pin4"]} becomes KiCad pad "1", the exported KiCad footprint is mislabeled even though the
circuit-json source and footprint geometry are correct.

This affects common real-world package patterns:

- SOIC/SSOP/TSSOP packages where one side is 1..N/2 and the other side is N..N/2+1
- connectors whose manufacturer pin numbers are gapped or non-1-indexed
- footprints generated from EasyEDA/LCSC where pads are listed in physical traversal order

## Real Examples Observed

For an MCP23017 SSOP-28 imported footprint, the source/EasyEDA physical order is:

bottom row left-to-right: pin1, pin2, ... pin14
top row left-to-right:    pin28, pin27, ... pin15

The circuit-json preserves that via port_hints.

KiCad export emits:

bottom row left-to-right: pad "1", pad "2", ... pad "14"
top row left-to-right:    pad "15", pad "16", ... pad "28"

So KiCad pad "15" is physically where EasyEDA/source pin 28 should be.

For a PJ-609 connector with source/EasyEDA pins 2,3,4,6,7,5, KiCad export emits pads 1,2,3,4,5,6.

## Likely Cause

In circuit-json-to-kicad, SMD and plated-hole pads appear to be created with a sequential local counter:

number: String(padNumber)

and padNumber is incremented as pads are emitted.

That means array order is treated as physical pin number.

## Suggested Fix

When converting pcb_smtpad and pcb_plated_hole to KiCad pads, derive the KiCad pad number from the pad’s
source port identity before falling back to sequence order.

Preferred order:

1. pad.pcb_port_id -> pcb_port.source_port_id -> source_port.pin_number
2. pin-like pad.port_hints, e.g. pin4, 4, A1
3. fallback sequential number only if no source identity exists

Pseudocode:
```
function getKiCadPadNumber(pad, ctx, fallbackNumber) {
  const pcbPort = ctx.db.pcb_port
    ?.list()
    .find((p) => p.pcb_port_id === pad.pcb_port_id)

  const sourcePort = pcbPort?.source_port_id
    ? ctx.db.source_port
        ?.list()
        .find((p) => p.source_port_id === pcbPort.source_port_id)
    : undefined

  if (sourcePort?.pin_number != null) {
    return String(sourcePort.pin_number)
  }

  const pinHint = pad.port_hints?.find((h) => /^pin[A-Za-z0-9_]+$/i.test(h))
  if (pinHint) return pinHint.replace(/^pin/i, "")

  const numericOrGridHint = pad.port_hints?.find((h) =>
    /^[A-Za-z]?\d+[A-Za-z0-9_]*$/i.test(h)
  )
  if (numericOrGridHint) return numericOrGridHint

  return String(fallbackNumber)
}
```
The exact implementation may differ, but the key invariant is:

> KiCad pad number should preserve source physical pin identity, not emitted pad array index.

### PR DESCRIPTION
**Pull request by Sang-it**
## Summary

- KiCad export was labelling pads by `pcb_smtpad` / `pcb_plated_hole` array order instead of by source pin identity, so a custom footprint declared in reverse physical order (`portHints={["pin4"]}` at x=-3, ..., `portHints={["pin1"]}` at x=3) came out with inverted KiCad pad labels.
- Added `getKiCadPadNumber` — walks `pcb_port → source_port.pin_number`, with fallbacks to pin-like `port_hints` (`"pin4"` → `"4"`, BGA-style `"A1"` → `"A1"`) and the existing sequential counter as last resort.
- Threaded the resolver through `convertSmdPads` / `convertPlatedHoles` as an optional `getPadNumber` callback, mirroring the existing `getNetInfo` pattern in `AddFootprintsStage`.

Fixes #212.

## Before vs after

Same four-pad footprint from the issue repro (`portHints` in reverse order):

| pad position `(at x y)` | before | after |
|---|---|---|
| `-3 0` | `pad "1"` | `pad "4"` |
| `-1 0` | `pad "2"` | `pad "3"` |
| ` 1 0` | `pad "3"` | `pad "2"` |
| ` 3 0` | `pad "4"` | `pad "1"` |

## Notes

- The pad UUID seed includes `padNumber` (`pad:${componentId}:${padNumber}:${x},${y}`), so UUIDs for affected pads will change once. This is desirable — UUIDs now track pin identity rather than array order, so reordering pads in source no longer churns them.
- `getPadNumber` is optional on both converter functions to keep the signatures backward-compatible for any external callers.
- Fallback counter keeps incrementing every iteration so unresolved pads on the sequence-number fallback path don't collide with each other.

## Test plan

- [x] New regression test `tests/pcb/repros/repro13-custom-footprint-pad-numbering.test.tsx` — exact repro from the issue, asserts pad `"4"` is at x=-3, pad `"1"` at x=3, etc.
- [x] `bun run typecheck` clean
- [x] `bun run format:check` clean
- [ ] CI green (including PNG snapshot tests that need `kicad-cli`)

### CODE REVIEW

File: lib/pcb/stages/utils/getKiCadPadNumber.ts [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+ * pin-like port_hints, and finally to a sequential number.
+ *
+ * Pad array order is NOT the physical pin number — this preserves the
+ * identity declared on the original `<smtpad portHints={["pin4"]} ... />`.
+ */
+export function getKiCadPadNumber(
+  pad: { pcb_port_id?: string; port_hints?: string[] },
+  db: CircuitJsonUtilObjects,
+  fallbackNumber: number,
+): string {
```
Comment (imrishabh18) [inline lib/pcb/stages/utils/getKiCadPadNumber.ts]: We follow a 2 param rule for our code style. Check this out - https://github.com/tscircuit/handbook/blob/main/guides/code.md#1-two-parameter-rule

**Review by imrishabh18 — COMMENTED** [review]
Looks good! see comments

File: lib/pcb/stages/utils/getKiCadPadNumber.ts (hunk 1 above)
Comment (seveibar) [reply lib/pcb/stages/utils/getKiCadPadNumber.ts]: yep was gonna say, and context-compatible options should always be the second parameter

File: lib/pcb/stages/footprints-stage-converters/convertPlatedHoles.ts [hunk 2]
```diff
@@ -10,16 +10,20 @@ export function convertPlatedHoles(
   componentId: string,
   startPadNumber: number,
   getNetInfo: (pcbPortId?: string) => PcbNetInfo | undefined,
+  getPadNumber?: (pad: PcbPlatedHole, fallback: number) => string,
```
Comment (seveibar) [inline lib/pcb/stages/footprints-stage-converters/convertPlatedHoles.ts]: this function is a nightmare, should have never been positional args. Try to make the problem better (staff should generally refactor where possible to our conventions) by accepting a context as the last parameter, and not passing `getPadNumber` into this function, since it can be created using the context

**Review by imrishabh18 — APPROVED** [review]
